#Tests SGN::Controller::AJAX::Search::Stock

use strict;
use warnings;

use lib 't/lib';
use SGN::Test::Fixture;
use Test::More;
use Test::WWW::Mechanize;
use SGN::Model::Cvterm;
use Data::Dumper;
use JSON;
local $Data::Dumper::Indent = 0;

my $f = SGN::Test::Fixture->new();
my $schema = $f->bcs_schema;

my $mech = Test::WWW::Mechanize->new(timeout=>30000);
my $response;

$mech->post_ok('http://localhost:3010/brapi/v1/token', [ "username"=> "janedoe", "password"=> "secretpw", "grant_type"=> "password" ]);
my $response = JSON::XS->new->decode($mech->content);
print STDERR Dumper $response;
is($response->{'metadata'}->{'status'}->[0]->{'message'}, 'Login Successfull');
my $sgn_session_id = $response->{access_token};
print STDERR $sgn_session_id."\n";

$mech->post_ok('http://localhost:3010/ajax/search/stocks', ['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ]);
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'recordsFiltered' => 2944,'draw' => undef,'data' => [['<a href="/stock/40326/view">BLANK</a>','<a href="/company/1">ImageBreed</a>','accession',undef,'','',''],['<a href="/stock/41284/view">CASS_6Genotypes_103</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41295/view">CASS_6Genotypes_104</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41296/view">CASS_6Genotypes_105</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41297/view">CASS_6Genotypes_106</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41298/view">CASS_6Genotypes_107</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41299/view">CASS_6Genotypes_201</a>','<a href="/company/1">ImageBreed</a>','plot',undef,'','',''],['<a href="/stock/41300/view">CASS_6Genotypes_202</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41301/view">CASS_6Genotypes_203</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/breeders/seedlot/41770">BLANK_001</a>','<a href="/company/1">ImageBreed</a>','seedlot',undef,'','','']],'recordsTotal' => 2944}, 'test stock search 1');

my $accession_type_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'accession', 'stock_type')->cvterm_id();
my $plot_type_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'plot', 'stock_type')->cvterm_id();
my $cross_type_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'cross', 'stock_type')->cvterm_id();
my $population_type_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'population', 'stock_type')->cvterm_id();

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "contains","any_name" => "test", "stock_type"=>'accession', "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'recordsTotal' => 27,'data' => [['<a href="/stock/38846/view">new_test_crossP001</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>',''],['<a href="/stock/38847/view">new_test_crossP002</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>',''],['<a href="/stock/38848/view">new_test_crossP003</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>',''],['<a href="/stock/38849/view">new_test_crossP004</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>',''],['<a href="/stock/38850/view">new_test_crossP005</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>',''],['<a href="/stock/38851/view">new_test_crossP006</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>',''],['<a href="/stock/38852/view">new_test_crossP007</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>',''],['<a href="/stock/38853/view">new_test_crossP008</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>',''],['<a href="/stock/41279/view">test_Germplasm</a>','<a href="/company/1">ImageBreed</a>','accession','Manihot esculenta','variety_17','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>, <a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/41785/view">test_Germplasm9</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','variety_1','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>','']],'draw' => undef,'recordsFiltered' => 27}, 'test stock search 2');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "contains","any_name" => "test", "stock_type"=>"plot", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'recordsTotal' => 939,'data' => [['<a href="/stock/40327/view">test_t1</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/40328/view">test_t10</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/40329/view">test_t100</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/40330/view">test_t101</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/40331/view">test_t102</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/40332/view">test_t103</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/40333/view">test_t104</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/40334/view">test_t105</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41782/view">Testing Plot</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41783/view">Testing Plot 2</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','','']],'draw' => undef,'recordsFiltered' => 939}, 'test stock search 3');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "contains","any_name" => "test", "stock_type"=>"cross", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'draw' => undef,'recordsFiltered' => 21,'data' => [['<a href="/cross/38845">new_test_cross</a>','<a href="/company/1">ImageBreed</a>','cross','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>',''],['<a href="/cross/41248">cross_test1</a>','<a href="/company/1">ImageBreed</a>','cross','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/cross/41249">cross_test4</a>','<a href="/company/1">ImageBreed</a>','cross','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/cross/41250">cross_test5</a>','<a href="/company/1">ImageBreed</a>','cross','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/cross/41251">cross_test6</a>','<a href="/company/1">ImageBreed</a>','cross','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/cross/41252">cross_test2</a>','<a href="/company/1">ImageBreed</a>','cross','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/cross/41253">cross_test3</a>','<a href="/company/1">ImageBreed</a>','cross','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/cross/41264">TestCross1</a>','<a href="/company/1">ImageBreed</a>','cross','Manihot esculenta','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/cross/41273">TestCross10</a>','<a href="/company/1">ImageBreed</a>','cross','Manihot esculenta','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/cross/41274">TestCross11</a>','<a href="/company/1">ImageBreed</a>','cross','Manihot esculenta','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>','']],'recordsTotal' => 21}, 'test stock search 4');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "contains","any_name" => "test", "stock_type"=>"population", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'draw' => undef,'recordsFiltered' => 5,'data' => [['<a href="/stock/41259/view">TestPopulation1</a>','<a href="/company/1">ImageBreed</a>','population','Manihot esculenta','','',''],['<a href="/stock/41260/view">TestPopulation2</a>','<a href="/company/1">ImageBreed</a>','population','Manihot esculenta','','',''],['<a href="/stock/41261/view">TestPopulation3</a>','<a href="/company/1">ImageBreed</a>','population','Manihot esculenta','','',''],['<a href="/stock/41262/view">TestPopulation4</a>','<a href="/company/1">ImageBreed</a>','population','Manihot esculenta','','',''],['<a href="/stock/41263/view">TestPopulation5</a>','<a href="/company/1">ImageBreed</a>','population','Manihot esculenta','','','']],'recordsTotal' => 5}, 'test stock search 5');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "contains","any_name" => "test", "stock_type"=>"accession", "person"=>"Jane,Doe", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'recordsTotal' => 7,'draw' => undef,'recordsFiltered' => 7,'data' => [['<a href="/stock/38873/view">test5P001</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38874/view">test5P002</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38875/view">test5P003</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38876/view">test5P004</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38877/view">test5P005</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/41279/view">test_Germplasm</a>','<a href="/company/1">ImageBreed</a>','accession','Manihot esculenta','variety_17','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>, <a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/41785/view">test_Germplasm9</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','variety_1','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>','']]}, 'test stock search 6');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "ends_with","any_name" => "001", "stock_type"=>"accession", "person"=>"Jane, Doe", "trait"=>"fresh root weight", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'draw' => undef,'recordsFiltered' => 2,'data' => [['<a href="/stock/38878/view">UG120001</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/39132/view">UG130001</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>','']],'recordsTotal' => 2}, "test stock search 7");

my $test_bp_id = $schema->resultset("Project::Project")->find({name=>'test'})->project_id;

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "contains","any_name" => "g", "stock_type"=>"accession", "person"=>"Jane, Doe", "breeding_program" => $test_bp_id, "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'recordsTotal' => 428,'data' => [['<a href="/stock/38878/view">UG120001</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38879/view">UG120002</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38880/view">UG120003</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38881/view">UG120004</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38882/view">UG120005</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38883/view">UG120006</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38884/view">UG120007</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38885/view">UG120008</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38886/view">UG120009</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/41279/view">test_Germplasm</a>','<a href="/company/1">ImageBreed</a>','accession','Manihot esculenta','variety_17','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>, <a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>','']],'draw' => undef,'recordsFiltered' => 428}, "test 8");

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "contains","any_name" => "t", "stock_type"=>"accession", "project" => "test_trial", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'draw' => undef,'recordsFiltered' => 5,'data' => [['<a href="/stock/38840/view">test_accession1</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','test_accession1_synonym1','',''],['<a href="/stock/38841/view">test_accession2</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','test_accession2_synonym1,test_accession2_synonym2','',''],['<a href="/stock/38842/view">test_accession3</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','test_accession3_synonym1','',''],['<a href="/stock/38843/view">test_accession4</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','',''],['<a href="/stock/38844/view">test_accession5</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','','']],'recordsTotal' => 5}, 'test stock search 9');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "stock_type"=>"accession", "year" => "2014", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'data' => [['<a href="/stock/38840/view">test_accession1</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','test_accession1_synonym1','',''],['<a href="/stock/38841/view">test_accession2</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','test_accession2_synonym1,test_accession2_synonym2','',''],['<a href="/stock/38842/view">test_accession3</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','test_accession3_synonym1','',''],['<a href="/stock/38843/view">test_accession4</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','',''],['<a href="/stock/38844/view">test_accession5</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','',''],['<a href="/stock/38878/view">UG120001</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38879/view">UG120002</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38880/view">UG120003</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38881/view">UG120004</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38882/view">UG120005</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>','']],'recordsFiltered' => 432,'draw' => undef,'recordsTotal' => 432}, 'test stock search 10');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "contains","any_name" => "g", "stock_type"=>"accession", "breeding_program" => $test_bp_id, "location"=>"test_location", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'data' => [['<a href="/stock/38878/view">UG120001</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38879/view">UG120002</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38880/view">UG120003</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38881/view">UG120004</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38882/view">UG120005</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38883/view">UG120006</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38884/view">UG120007</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38885/view">UG120008</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/38886/view">UG120009</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>',''],['<a href="/stock/41279/view">test_Germplasm</a>','<a href="/company/1">ImageBreed</a>','accession','Manihot esculenta','variety_17','<a href="/solpeople/personal-info.pl?sp_person_id=40">John Doe</a>, <a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>','']],'recordsFiltered' => 428,'draw' => undef,'recordsTotal' => 428}, 'test stock search 11');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "contains","any_name" => "t", "stock_type"=>"plot", "project" => "test_trial", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'data' => [['<a href="/stock/38857/view">test_trial21</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/38858/view">test_trial22</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/38859/view">test_trial23</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/38860/view">test_trial24</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/38866/view">test_trial210</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/38867/view">test_trial211</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/38868/view">test_trial212</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/38869/view">test_trial213</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/38870/view">test_trial214</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/38871/view">test_trial215</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','','']],'draw' => undef,'recordsFiltered' => 15,'recordsTotal' => 15}, 'test stock search 12');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "stock_type"=>"plot", "year" => "2014", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'recordsTotal' => 1014,'draw' => undef,'recordsFiltered' => 1014,'data' => [['<a href="/stock/39311/view">KASESE_TP2013_1003</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/39322/view">KASESE_TP2013_1009</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/39350/view">KASESE_TP2013_1008</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/39493/view">KASESE_TP2013_1001</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/39632/view">KASESE_TP2013_1004</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/39691/view">KASESE_TP2013_1000</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/39819/view">KASESE_TP2013_1002</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/39836/view">KASESE_TP2013_1007</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/39846/view">KASESE_TP2013_1005</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','',''],['<a href="/stock/39919/view">KASESE_TP2013_1006</a>','<a href="/company/1">ImageBreed</a>','plot','Solanum lycopersicum','','','']]}, 'test stock search 13');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "any_name_matchtype" => "contains","any_name" => "g", "stock_type"=>"plot", "breeding_program" => $test_bp_id, "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'draw' => undef,'recordsFiltered' => 328,'data' => [['<a href="/stock/41284/view">CASS_6Genotypes_103</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41285/view">CASS_6Genotypes_205</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41295/view">CASS_6Genotypes_104</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41296/view">CASS_6Genotypes_105</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41297/view">CASS_6Genotypes_106</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41298/view">CASS_6Genotypes_107</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41299/view">CASS_6Genotypes_201</a>','<a href="/company/1">ImageBreed</a>','plot',undef,'','',''],['<a href="/stock/41300/view">CASS_6Genotypes_202</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41301/view">CASS_6Genotypes_203</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41302/view">CASS_6Genotypes_204</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','','']],'recordsTotal' => 328}, 'test stock search 14');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, 'length'=>10, 'start'=>0, "stock_type"=>"plot", "location"=>"test_location", "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'draw' => undef,'recordsFiltered' => 1956,'data' => [['<a href="/stock/41284/view">CASS_6Genotypes_103</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41285/view">CASS_6Genotypes_205</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41295/view">CASS_6Genotypes_104</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41296/view">CASS_6Genotypes_105</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41297/view">CASS_6Genotypes_106</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41298/view">CASS_6Genotypes_107</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41299/view">CASS_6Genotypes_201</a>','<a href="/company/1">ImageBreed</a>','plot',undef,'','',''],['<a href="/stock/41300/view">CASS_6Genotypes_202</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41301/view">CASS_6Genotypes_203</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','',''],['<a href="/stock/41302/view">CASS_6Genotypes_204</a>','<a href="/company/1">ImageBreed</a>','plot','Manihot esculenta','','','']],'recordsTotal' => 1956}, 'test stock search 15');


$mech->post_ok('http://localhost:3010/stock/prop/add',['sgn_session_id'=>$sgn_session_id, "stock_id"=>"38842", "prop"=>"organization_name_1", "prop_type"=>"organization"] );
$response = decode_json $mech->content;
print STDERR Dumper $response;
$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, "editable_stockprop_values" => encode_json({"organization"=>{"matchtype"=>"contains", "value"=>"organization_name_1"}})] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'data' => [['<a href="/stock/38842/view">test_accession3</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','test_accession3_synonym1','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>']],'recordsFiltered' => 1,'draw' => undef,'recordsTotal' => 1}, 'test stock search 16');

$mech->post_ok('http://localhost:3010/ajax/search/stocks',['sgn_session_id'=>$sgn_session_id, "editable_stockprop_values" => encode_json({"organization"=>{"matchtype"=>"contains", "value"=>"organization_name_1"}}), "extra_stockprop_columns_view" => encode_json({"organization"=>1}), "stockprop_extra_columns_view_array"=> encode_json(["organization"]) ] );
$response = decode_json $mech->content;
print STDERR Dumper $response;

is_deeply($response, {'data' => [['<a href="/stock/38842/view">test_accession3</a>','<a href="/company/1">ImageBreed</a>','accession','Solanum lycopersicum','test_accession3_synonym1','<a href="/solpeople/personal-info.pl?sp_person_id=41">Jane Doe</a>','organization_name_1']],'recordsTotal' => 1,'recordsFiltered' => 1,'draw' => undef}, 'test stock search 16');

done_testing();
